export enum DepartmentTypeEnum {
  HR = 'HR',
  ENGINEERING = 'ENGINEERING',
  FINANCE = 'FINANCE',
  SALES = 'SALES',
  MARKETING = 'MARKETING',
  OPERATIONS = 'OPERATIONS',
  ADMINISTRATION ='ADMINISTRATION'
}

